#!/usr/bin/env zsh
# A program to convert Firefox JSON bookmark dumps to TSV with timestamp information.
# Pipe-in/Pipe-out, relies on GNU Awk (probably)

jq -r 'recurse(.children[]?) | if .type == "text/x-moz-place" then [ .title , .uri , .tags , .dateAdded , .lastModified ] else (.title as $title | .annos[]? | select(.name == "livemark/siteURI") | [ $title , .value , "RSS Feed" , .dateAdded , .lastModified ]) end | @tsv' | awk -F'\t' '{ da = sprintf("%d", $4/1000000); lm = sprintf("%d", $5/1000000); dac = "date -d @" da; dac | getline dar; close(dar); lmc = "date -d @" lm; lmc | getline lmr; close(lmc); print $1 "\t" $2 "\t" $3 "\t" dar "\t" lmr }'
