#!/usr/bin/env zsh
# The -t stuff with sort will work on bash, too

jq -r 'recurse(.children[]?) | if .type == "text/x-moz-place" then [ .title , .uri , .tags , .dateAdded , .lastModified ] else (.title as $title | .dateAdded as $dateAdded | .lastModified as $lastModified | .annos[]? | select(.name == "livemark/siteURI") | [ $title , .value , "RSS Feed" , $dateAdded , $lastModified ]) end | @tsv' | sort -t$'\t' -k 4 -n | awk -F'\t' '{ da = sprintf("%d", $4/1000000); lm = sprintf("%d", $5/1000000); dac = "date -d @" da; dac | getline dar; close(dac); lmc = "date -d @" lm; lmc | getline lmr; close(lmc); print $1 "\t" $2 "\t" $3 "\t" dar "\t" lmr }'
