#!/bin/bash
# Convert a Mozilla Firefox SessionSaver JSON(-ish) session file to a tab-separated value file with page titles and URLs
# Pipe-in/pipe-out

tr '\r' '\n' | drop 4 | jq -r '.windows[] | .tabs[] | recurse(.entries[]?) | [ .title, .url ] | @tsv'
